"""Notification types và default channels."""

# Notification types
TASK_ASSIGNED = "TASK_ASSIGNED"
TASK_COMPLETED = "TASK_COMPLETED"
TASK_OVERDUE = "TASK_OVERDUE"
WORKFLOW_ALERT = "WORKFLOW_ALERT"
LEAD_ASSIGNED = "LEAD_ASSIGNED"
STUDENT_AT_RISK = "STUDENT_AT_RISK"
PAYMENT_OVERDUE = "PAYMENT_OVERDUE"
PAYMENT_RECEIVED = "PAYMENT_RECEIVED"
ENROLLMENT_EXPIRING = "ENROLLMENT_EXPIRING"
EXAM_PUBLISHED = "EXAM_PUBLISHED"
SYSTEM_ANNOUNCEMENT = "SYSTEM_ANNOUNCEMENT"

ALL_TYPES = [
    TASK_ASSIGNED,
    TASK_COMPLETED,
    TASK_OVERDUE,
    WORKFLOW_ALERT,
    LEAD_ASSIGNED,
    STUDENT_AT_RISK,
    PAYMENT_OVERDUE,
    PAYMENT_RECEIVED,
    ENROLLMENT_EXPIRING,
    EXAM_PUBLISHED,
    SYSTEM_ANNOUNCEMENT,
]

# Vietnamese labels
TYPE_LABELS = {
    TASK_ASSIGNED: "Công việc được giao",
    TASK_COMPLETED: "Công việc hoàn thành",
    TASK_OVERDUE: "Công việc quá hạn",
    WORKFLOW_ALERT: "Cảnh báo tự động",
    LEAD_ASSIGNED: "Lead được giao",
    STUDENT_AT_RISK: "Học viên có nguy cơ",
    PAYMENT_OVERDUE: "Thanh toán quá hạn",
    PAYMENT_RECEIVED: "Đã nhận thanh toán",
    ENROLLMENT_EXPIRING: "Ghi danh sắp hết hạn",
    EXAM_PUBLISHED: "Kết quả kiểm tra đã công bố",
    SYSTEM_ANNOUNCEMENT: "Thông báo hệ thống",
}

# Channels
CHANNEL_IN_APP = "IN_APP"
CHANNEL_EMAIL = "EMAIL"
CHANNEL_SMS = "SMS"
CHANNEL_PUSH = "PUSH"

ALL_CHANNELS = [CHANNEL_IN_APP, CHANNEL_EMAIL, CHANNEL_SMS, CHANNEL_PUSH]

CHANNEL_LABELS = {
    CHANNEL_IN_APP: "Trong ứng dụng",
    CHANNEL_EMAIL: "Email",
    CHANNEL_SMS: "SMS",
    CHANNEL_PUSH: "Push",
}

# Notification types không thể tắt (quan trọng)
ALWAYS_ON_TYPES = {SYSTEM_ANNOUNCEMENT}